name: base
channels:
  - pytorch
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=2.106=mkl
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=h0dc2134_1
  - brotli-bin=1.1.0=h0dc2134_1
  - brotli-python=1.1.0=py311hdf8f085_1
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.33.0=h51dda26_0
  - ca-certificates=2024.8.30=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py311h6e3bf6f_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.7.1=py311h6eed73b_0
  - conda-libmamba-solver=24.7.0=pyhd8ed1ab_0
  - conda-package-handling=2.3.0=pyh7900ff3_0
  - conda-package-streaming=0.10.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py311h1d816ee_0
  - cpuonly=2.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py311hbafa61a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - equinox=0.11.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fmt=10.2.1=h7728843_0
  - fonttools=4.53.1=py311h72ae277_0
  - freetype=2.12.1=h60636b9_2
  - frozendict=2.4.4=py311h72ae277_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.3.0=hf036a51_2
  - gmpy2=2.1.5=py311hf411314_2
  - gurobi=11.0.3=py311_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py311h4faab6c_102
  - hdf5=1.14.3=nompi_h687a608_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.28.0=pyh707e725_0
  - jax=0.4.31=pyhd8ed1ab_0
  - jaxlib=0.4.31=cpu_py311h0fc882a_0
  - jaxopt=0.8.3=pyhd8ed1ab_0
  - jaxtyping=0.2.33=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h6eed73b_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h6eed73b_0
  - kiwisolver=1.4.5=py311h5fe6e05_1
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20240116.2=cxx17_hf036a51_1
  - libaec=1.1.3=h73e2aa4_0
  - libarchive=3.7.4=h20e244c_0
  - libblas=3.9.0=6_mkl
  - libbrotlicommon=1.1.0=h0dc2134_1
  - libbrotlidec=1.1.0=h0dc2134_1
  - libbrotlienc=1.1.0=h0dc2134_1
  - libcblas=3.9.0=6_mkl
  - libcurl=8.9.1=hfcf2730_0
  - libcxx=18.1.8=heced48a_4
  - libdeflate=1.21=hfdf4475_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libexpat=2.6.2=h73e2aa4_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libgrpc=1.62.2=h384b2fc_0
  - libiconv=1.17=hd75f5a5_2
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=6_mkl
  - liblapacke=3.9.0=6_mkl
  - libmamba=1.5.8=ha449628_0
  - libmambapy=1.5.8=py311h6c5c7ae_0
  - libnghttp2=1.58.0=h64cf6d3_1
  - libopenblas=0.3.27=openmp_h8869122_1
  - libpng=1.6.43=h92b6c6a_0
  - libprotobuf=4.25.3=h4e4d658_0
  - libre2-11=2023.09.01=h81f5012_2
  - libsodium=1.0.18=hbcb3906_1
  - libsolv=0.7.30=h69d5d9b_0
  - libsqlite=3.46.0=h1b8f9f3_0
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.6.0=h603087a_4
  - libwebp-base=1.4.0=h10d778d_0
  - libxcb=1.16=h0dc2134_0
  - libxml2=2.12.7=heaf3512_4
  - libzlib=1.3.1=h87427d6_1
  - lineax=0.0.5=pyhd8ed1ab_0
  - llvm-openmp=18.1.8=h15ab845_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - lzo=2.10=h10d778d_1001
  - markupsafe=2.1.5=py311h3336109_1
  - matplotlib-base=3.9.2=py311hf31e254_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - menuinst=2.1.2=py311h6eed73b_0
  - mkl=2020.4=h08c4f10_301
  - ml_dtypes=0.4.0=py311hfdcbad3_1
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h5846eda_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - numpy=1.24.4=py311hc44ba51_0
  - openjpeg=2.5.2=h7310d3a_0
  - openssl=3.3.2=hd23fc13_0
  - opt-einsum=3.3.0=hd8ed1ab_2
  - opt_einsum=3.3.0=pyhc1e730c_2
  - ott-jax=0.4.7=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py311haeb46be_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py311h2755ac0_0
  - pip=24.2=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pot=0.9.4=py311hfdcbad3_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - protobuf=4.25.3=py311h6b31176_1
  - psutil=6.0.0=py311h72ae277_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h2725bcf_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=h657bba9_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytorch=2.2.2=py3.11_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h3336109_1
  - pyzmq=26.1.0=py311hdb04418_0
  - qhull=2020.2=h3c5361c_5
  - re2=2023.09.01=hb168e87_2
  - readline=8.2=h9e318b2_1
  - reproc=14.2.4.post0=h10d778d_1
  - reproc-cpp=14.2.4.post0=h93d8f39_1
  - requests=2.32.3=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py311he705e18_0
  - ruamel.yaml.clib=0.2.8=py311he705e18_0
  - scikit-learn=1.5.2=py311ha1d5734_1
  - scipy=1.14.0=py311h40a1ab3_2
  - sentry-sdk=2.15.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py311h3336109_1
  - setuptools=72.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.3=pypyh2585a3b_103
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h1abcd95_1
  - torchaudio=2.2.2=py311_cpu
  - torchvision=0.17.2=py311_cpu
  - tornado=6.4.1=py311h72ae277_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - typeguard=2.13.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wandb=0.17.3=py311h3408931_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - yaml-cpp=0.8.0=he965462_0
  - zeromq=4.3.5=hde137ed_4
  - zipp=3.20.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py311h51fa951_0
  - zstd=1.5.6=h915ae27_0
prefix: /Users/zeyichen/opt/anaconda3/envs/WB
